import java.util.Scanner;

public class NumberGame{
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

        System.out.println("Welcome to the Number Game!");
        System.out.println("Let us go over the rules of the game : ");
        System.out.println("A random number will be generated by the system between 1 to 100. You will get 5 trials to guess the number.");
        System.out.println("If your number is less than the generated number the output will be displayed as LOW.");
        System.out.println("If your number is more than the generated number the output will be displayed as HIGH.");
        System.out.println("If your number is equal to the generated number or you have exhausted your trials, the game will terminate.");
        System.out.println("LET'S BEGIN!");

        
        int trials = 5;
        int score = 0;
        System.out.println("How many rounds do you want to play this game for?");
        int rounds = scan.nextInt();
        
        for(int j = 0; j < rounds; j++){
            System.out.println("Round " + (j +1));
            int number = (int)(Math.random()*100) + 1;
            for(int i = 0; i<trials; i++){
            System.out.println("Attempt " + (i+1) + " : Guess the number : ");
            int guess = scan.nextInt();

            if (guess == number) {
                System.out.println("Congratulations. You guessed the number.");
                score += 1;
                break;
            } else if(guess > number && i != (trials-1) ){
                System.out.println("Your guess is too HIGH. Try again.");
            } else if (guess < number && i != (trials-1)){
                System.out.println("Your guess is too LOW. Try again.");
            }
            if (i == (trials - 1)) {
                if(guess > number) {
                    System.out.println("Your guess is too HIGH.");
                    System.out.println("You have exhausted all your trials.");
                    System.out.println("The correct number was : " + number);
                } else if (guess < number) {
                    System.out.println("Your guess is too LOW.");
                    System.out.println("You have exhausted all your trials.");
                    System.out.println("The correct number was : " + number);
                }
            }
            
            }
        }
            scan.close();
            System.out.println("Your score is : " + score + "/" + rounds);
        }
    }
